////////////////////////////////////////////////////////////////////
// MELEZE : A DSGE model for fiscal simulations in a monetary union
// Campagne B. & Poissonnier A., G2016/05, Insee.
//
// Programme appelé par "looping_meleze_DT_fig(...).m" : ne pas modifier
////////////////////////////////////////////////////////////////////


@#include ".\SAVED_Inputs\meleze_variables(block).mod"
@#include "calib_temp.txt"

@#include "EulerORBR_temp.txt" 
@#include "DummiesORNot_temp.txt" 
@#define PHIRULE= 0
@#define NOTAX= 1
// takes the equation from the model
@#include ".\SAVED_Inputs\meleze_model(block).mod" 

// takes the simulations generated by looping_meleze.m
@#include "shocks_temp.txt" 

